# 最大值最小值归一化

## 引入

In [1]:
import numpy as np
from sklearn import datasets

In [2]:
#加载鸢尾花数据集
iris=datasets.load_iris()

In [3]:
X=iris.data
y=iris.target

In [4]:
X[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [5]:
np.max(X[:,0])

7.9

In [6]:
np.min(X[:,0])

4.3

In [7]:
#X[:,0]=(X[:,0]-np.min(X[:,0]))/(np.max(X[:,0])-np.min(X[:,0]))

In [8]:
#X[:5,0]

## 主要操作

In [9]:
for i in range(4):
     X[:,i]=(X[:,i]-np.min(X[:,i]))/(np.max(X[:,i])-np.min(X[:,i]))

In [10]:
X[:5]

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667]])

# 零均值归一化

## 引入

In [11]:
iris=datasets.load_iris()
X=iris.data
y =iris.target

In [12]:
X[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [13]:
np.mean(X[:,0])

5.843333333333334

In [14]:
np.std(X[:,0])

0.8253012917851409

In [15]:
#X[:,0]=(X[:,0]-np.mean(X[:,0]))/np.std(X[:,0])

In [16]:
X[:5,0]

array([5.1, 4.9, 4.7, 4.6, 5. ])

In [17]:
np.mean(X[:,0])

5.843333333333334

In [18]:
np.std(X[:,0])

0.8253012917851409

## 主要操作

In [20]:
for i in range(4):
     X[:,i]=(X[:,i]-np.mean(X[:,i]))/np.std(X[:,i])

In [21]:
X[:5]

array([[-0.90068117,  1.01900435, -1.34022653, -1.3154443 ],
       [-1.14301691, -0.13197948, -1.34022653, -1.3154443 ],
       [-1.38535265,  0.32841405, -1.39706395, -1.3154443 ],
       [-1.50652052,  0.09821729, -1.2833891 , -1.3154443 ],
       [-1.02184904,  1.24920112, -1.34022653, -1.3154443 ]])

# scikit-learn中的StandardScaler

## 零均值归一化 from sklearn.preprocessing import StandardScaler

In [22]:
iris=datasets.load_iris()
X=iris.data
y =iris.target

In [23]:
X[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [24]:
from sklearn.preprocessing import StandardScaler

In [25]:
standar_scaler=StandardScaler()#创建StandardScaler类的实例

In [27]:
standar_scaler.fit(X)#已经求出所有东西保存在实例中

StandardScaler()

In [28]:
standar_scaler.mean_

array([5.84333333, 3.05733333, 3.758     , 1.19933333])

In [30]:
standar_scaler.scale_#四类特征的标准差

array([0.82530129, 0.43441097, 1.75940407, 0.75969263])

In [32]:
standar_scaler.transform(X)#零均值归一化结果

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

In [33]:
X=standar_scaler.transform(X)

In [34]:
X[:5,0]

array([-0.90068117, -1.14301691, -1.38535265, -1.50652052, -1.02184904])

## 最值归一化 from sklearn.preprocessing import MinMaxScaler

In [36]:
from sklearn.preprocessing import MinMaxScaler
iris=datasets.load_iris()
X=iris.data
y =iris.target

In [37]:
minmax_scaler=MinMaxScaler()

In [38]:
minmax_scaler.fit(X)

MinMaxScaler()

In [39]:
minmax_scaler.min_

array([-1.19444444, -0.83333333, -0.16949153, -0.04166667])

In [40]:
result=minmax_scaler.transform(X)
result

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.22222222, 0.625     ,