In [1]:
import numpy as np
from sklearn import datasets

In [4]:
#加载鸢尾花数据集
iris=datasets.load_iris()
X=iris.data
y=iris.target.copy()
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
#转为二分类问题
y[y!=0]=1
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=666)

logistic_regression=LogisticRegression()
logistic_regression.fit(X_train,y_train)
y_predict=logistic_regression.predict(X_test)

# 手动实现

In [7]:
TN=np.sum((y_predict==0)&(y_test==0))
TN

10

In [10]:
FP=np.sum((y_predict==1)&(y_test==0))
FP

0

In [11]:
FN=np.sum((y_predict==0)&(y_test==1))
FN

0

In [12]:
TP=np.sum((y_predict==1)&(y_test==1))
TP

28

In [14]:
confusion_martix=np.array([
    [TN,FP],
    [FN,TP]
])
confusion_martix

array([[10,  0],
       [ 0, 28]])

In [15]:
precision=TP/(TP+FP)
precision

1.0

In [16]:
recall=TP/(FN+TP)
recall

1.0

In [17]:
f1_score=2*precision*recall/(precision+recall)
f1_score

1.0

# scikit-learn中封装实现

In [24]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_predict)

array([[10,  0],
       [ 0, 28]], dtype=int64)

In [25]:
from sklearn.metrics import precision_score
precision_score(y_test,y_predict)

1.0

In [26]:
from sklearn.metrics import recall_score
recall_score(y_test,y_predict)

1.0

In [28]:
from sklearn.metrics import f1_score
f1_score(y_test,y_predict)

1.0