## min,max,sum,mean(均值),median(中位数),std(标准差),var(方差),ptp（极差)，percentile(求分位数),cumsum(累加),diff(两个相邻的行与行或列于列相减),prod(将每行或每列所有数相乘)

In [1]:
import numpy as np
X=np.arange(5000000)
X

array([      0,       1,       2, ..., 4999997, 4999998, 4999999])

In [2]:
np.min(X)

0

In [3]:
np.max(X)

4999999

In [4]:
%time min(X)

CPU times: total: 234 ms
Wall time: 232 ms


0

In [5]:
%time np.min(X)

CPU times: total: 0 ns
Wall time: 1.99 ms


0

In [10]:
Y=X.reshape(5,-1)
Y

array([[      0,       1,       2, ...,  999997,  999998,  999999],
       [1000000, 1000001, 1000002, ..., 1999997, 1999998, 1999999],
       [2000000, 2000001, 2000002, ..., 2999997, 2999998, 2999999],
       [3000000, 3000001, 3000002, ..., 3999997, 3999998, 3999999],
       [4000000, 4000001, 4000002, ..., 4999997, 4999998, 4999999]])

In [11]:
np.min(Y,axis=0)

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [12]:
np.min(Y,axis=1)

array([      0, 1000000, 2000000, 3000000, 4000000])

In [14]:
X=np.linspace(1,20,20).reshape(4,5)
X

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.]])

In [15]:
np.sum(X,axis=0)

array([34., 38., 42., 46., 50.])

In [16]:
np.sum(X,axis=1)

array([15., 40., 65., 90.])

In [17]:
np.mean(X)

10.5

In [18]:
np.median(X)

10.5

In [19]:
np.std(X)

5.766281297335398

In [20]:
np.var(X)

33.25

In [27]:
Z=np.random.normal(0,10,100000)
np.mean(Z),np.std(Z)

(0.024285941115663446, 10.019934563821444)

In [28]:
np.ptp(X)

19.0

In [32]:
q=np.linspace(0,100,5)

In [33]:
q,np.percentile(X,q)#中位数，4分位数等等

(array([  0.,  25.,  50.,  75., 100.]),
 array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ]))

In [37]:
X

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.]])

In [36]:
np.cumsum(X,axis=1)

array([[ 1.,  3.,  6., 10., 15.],
       [ 6., 13., 21., 30., 40.],
       [11., 23., 36., 50., 65.],
       [16., 33., 51., 70., 90.]])

In [38]:
np.cumsum(X,axis=0)

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 7.,  9., 11., 13., 15.],
       [18., 21., 24., 27., 30.],
       [34., 38., 42., 46., 50.]])

In [39]:
np.diff(X,axis=1)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [41]:
np.diff(X,axis=0)

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [42]:
np.prod(X,axis=1)

array([1.20000e+02, 3.02400e+04, 3.60360e+05, 1.86048e+06])