# argsort
# argmin
# argmax
# argpartition

# 最大值最小值

In [1]:
import numpy as np
x=np.random.normal(0,1,size=1000000)
x

array([ 0.88278136, -1.44819996,  0.22217317, ...,  0.8003861 ,
       -0.37943751, -0.84830315])

In [2]:
np.min(x)

-4.8049009335693755

In [3]:
np.max(x)

4.688561358770962

In [4]:
np.argmin(x)

804451

In [5]:
x[np.argmin(x)]

-4.8049009335693755

# 排序

In [7]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.random.shuffle(x)#shuffle打乱顺序
x

array([5, 2, 1, 9, 4, 0, 3, 6, 8, 7])

In [14]:
np.sort(x)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
x#由此可见numpy的sort方法不会修改原数组，而是将结果放进了一个新数组

array([5, 2, 1, 9, 4, 0, 3, 6, 8, 7])

In [20]:
x.sort()
x#python原生的排序方法会修改原数组

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

# 使用索引

In [23]:
np.random.shuffle(x)
x

array([0, 1, 4, 7, 8, 6, 3, 2, 5, 9])

In [24]:
np.argsort(x)

array([0, 1, 7, 6, 2, 8, 5, 3, 4, 9], dtype=int64)

# partition分区

In [25]:
np.partition(x,5)

array([3, 2, 4, 0, 1, 5, 6, 7, 8, 9])

In [26]:
np.argpartition(x,5)

array([6, 7, 2, 0, 1, 8, 5, 3, 4, 9], dtype=int64)

# 高维情况

In [28]:
X=np.random.randint(10,size=(5,5))
X

array([[7, 6, 9, 9, 2],
       [6, 1, 1, 7, 8],
       [5, 3, 8, 6, 6],
       [6, 1, 9, 5, 5],
       [2, 2, 9, 4, 4]])

In [35]:
np.sort(X)#实际后面还有个axis参数，默认值为1行排序

array([[2, 6, 7, 9, 9],
       [1, 1, 6, 7, 8],
       [3, 5, 6, 6, 8],
       [1, 5, 5, 6, 9],
       [2, 2, 4, 4, 9]])

In [42]:
np.argsort(X,axis=0)

array([[4, 1, 1, 4, 0],
       [2, 3, 2, 3, 4],
       [1, 4, 0, 2, 3],
       [3, 2, 3, 1, 2],
       [0, 0, 4, 0, 1]], dtype=int64)

In [53]:
np.partition(X,2,axis=1)

array([[2, 6, 7, 9, 9],
       [1, 1, 6, 7, 8],
       [3, 5, 6, 8, 6],
       [1, 5, 5, 6, 9],
       [2, 2, 4, 9, 4]])

In [63]:
np.argpartition(X,2,axis=1)

array([[4, 1, 0, 3, 2],
       [1, 2, 0, 3, 4],
       [1, 0, 3, 2, 4],
       [1, 3, 4, 0, 2],
       [0, 1, 3, 2, 4]], dtype=int64)