In [22]:
import numpy as np
x=np.arange(10)
#np.random.shuffle(x)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
x[2:8]

array([2, 3, 4, 5, 6, 7])

In [24]:
x[2:8:2]

array([2, 4, 6])

In [27]:
[x[2],x[5],x[8]]#数组中随便取数一般方法

[2, 5, 8]

In [28]:
index=[2,5,8]#数组中随便取数便捷方法
x[index]

array([2, 5, 8])

## 神奇索引用于二维数组

In [40]:
X=x.reshape(2,-1)
X

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [41]:
row=np.array([0,1,0])
col=np.array([0,2,4])
X[row,col]

array([0, 7, 4])

In [42]:
X[0,col]#取第0行的col

array([0, 2, 4])

In [49]:
X[row,:2]

array([[0, 1],
       [5, 6],
       [0, 1]])

### 传入的索引可以为bool类型

In [50]:
col=[True,False,True,False,True]
X[0,col]

array([0, 2, 4])

## 比较

In [51]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
x<5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [53]:
x>=2

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [54]:
x==3

array([False, False, False,  True, False, False, False, False, False,
       False])

In [55]:
x!=3

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True])

In [56]:
x*x==9

array([False, False, False,  True, False, False, False, False, False,
       False])

In [57]:
X>1

array([[False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 比较与神奇索引的使用

In [58]:
x[x>3]

array([4, 5, 6, 7, 8, 9])

In [59]:
x[x%2==0]

array([0, 2, 4, 6, 8])

In [61]:
X[X>1]

array([2, 3, 4, 5, 6, 7, 8, 9])

## 比较的更多应用

In [62]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
np.count_nonzero(x<5)

5

In [65]:
x<5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [66]:
np.sum(x<5)

5

In [68]:
np.any(x<0)

False

In [69]:
np.any(x>5)

True

In [70]:
np.all(x>0)

False

In [71]:
np.all(x<10)

True

In [72]:
X

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [77]:
np.sum(X%2==0)

5

In [78]:
np.sum(X%2==0,axis=1)

array([3, 2])

In [79]:
np.sum(X%2==0,axis=0)

array([1, 1, 1, 1, 1])

In [80]:
np.all(X>2,axis=0)

array([False, False, False,  True,  True])

## 与&或|非~

In [81]:
X

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [82]:
np.sum((X<5)&(X>1))

3

In [83]:
np.sum((X<1)|(X>6))

4

In [84]:
np.sum(~(X==0))

9