In [1]:
import numpy as np

#  创建Numpy数组

In [2]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [3]:
A=np.array([
    [1,2,3],
    [4,5,6]
])
A

array([[1, 2, 3],
       [4, 5, 6]])

# Numpy 数组的属性
### ndim维度数量
### shape 数组的形状或维度
### size 数组中元素总个数
### dtype 数组中的元素类型


In [4]:
a.ndim

1

In [5]:
A.ndim

2

In [6]:
a.shape

(6,)

In [7]:
A.shape

(2, 3)

In [8]:
a.size

6

In [9]:
A.size

6

In [10]:
a.dtype

dtype('int32')

In [11]:
A.dtype

dtype('int32')

# 创建数组的便捷函数
### ones创建全是1的数组：第一个参数为数组形状,第二个参数为元素类型，一维(n，dtype)，二维（（n,m）,dtype）元素类型可省略
### np.ones_like(数组名)创建一个形状完全相同但全为1的矩阵

In [12]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.ones(8).dtype

dtype('float64')

In [14]:
np.ones(8,dtype='int64')

array([1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [15]:
np.ones(shape=(2,4))#np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.ones_like(A)

array([[1, 1, 1],
       [1, 1, 1]])

## np.zeros用法与ones完全相同不过元素均为0

In [17]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.zeros_like(A)

array([[0, 0, 0],
       [0, 0, 0]])

## np.full指定数值，第一个参数数组形状，第二个指定值，第三个元素类型，其余用法同上

In [20]:
np.full(8,666)

array([666, 666, 666, 666, 666, 666, 666, 666])

In [21]:
np.full((2,4),666)

array([[666, 666, 666, 666],
       [666, 666, 666, 666]])

In [22]:
np.full(8,666,dtype='int64')

array([666, 666, 666, 666, 666, 666, 666, 666], dtype=int64)

In [23]:
np.full_like(A,666)

array([[666, 666, 666],
       [666, 666, 666]])

##  np.empty创建一个空数组数值全为随即值

In [24]:
np.empty(10)

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 8.45593934e-307,
       1.89146896e-307, 7.56571288e-307, 3.11525958e-307, 1.24610723e-306,
       1.29061142e-306, 5.53353523e-322])

In [25]:
np.empty((3,4))

array([[1.31870854e-311, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 4.01471603e-057, 1.39511377e-075,
        7.46185552e-038],
       [7.60117505e-042, 9.68037251e-071, 2.44798521e-056,
        3.30462159e+179]])

In [26]:
np.empty_like(A)

array([[0, 0, 0],
       [0, 0, 0]])

## arange 

In [27]:
np.arange(10)#创建一个10个元素等差数组

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.arange(1,10,2)#第一个参数起始位，第二个参数截止位但不包含，第三个参数步长

array([1, 3, 5, 7, 9])

In [29]:
np.arange(10).reshape(2,5)#将数组形状改变

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## linspace也能创建等差数组，但可以指定数组数量

In [30]:
np.linspace(0,10,5)#起始位，终止位包含，范围区间内生成数的数量

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

# random 模块
## random

In [31]:
np.random.random()#返回0到1的随机数不包含1

0.5756280927384909

In [32]:
np.random.random(5)#返回n个0到1的随机数

array([0.42777391, 0.03338251, 0.435999  , 0.61853333, 0.82372239])

In [2]:
np.random.random((2,4))#返回二维数组，即参数为数组形状

array([[0.92398757, 0.85558067, 0.23281428, 0.27227883],
       [0.77328539, 0.66008713, 0.04025843, 0.72525644]])

## rand
## 与random用法相同，唯一不同是random传入元组，rand不用传入元组

In [34]:
np.random.rand()

0.2953723997404256

In [35]:
np.random.rand(5)

array([0.18624173, 0.29104033, 0.96308877, 0.995852  , 0.19208419])

In [36]:
np.random.rand(2,3,4)

array([[[0.65254763, 0.73186303, 0.34191884, 0.27497439],
        [0.63655506, 0.08368424, 0.97305793, 0.60455621],
        [0.42255922, 0.91574736, 0.1769369 , 0.43866625]],

       [[0.80693309, 0.90619737, 0.00213923, 0.88903332],
        [0.6768182 , 0.1011234 , 0.35256731, 0.64098086],
        [0.94909562, 0.56447012, 0.14640666, 0.12844225]]])

## randint 获得随机整数

In [37]:
np.random.randint(5)#返回0到5之间的随机数不包含5

2

In [38]:
np.random.randint(5,10)#返回5到10之间的随机数包含5不包含10

6

In [39]:
np.random.randint(5,10,8)#5到10之间生成8个随机数，np.random.randint(5,10,size=8)size参数可以传入元组见下

array([9, 8, 8, 9, 8, 6, 5, 6])

In [40]:
np.random.randint(5,10,(2,4))#np.random.randint(5,10,size=(2,4))

array([[9, 5, 7, 9],
       [6, 5, 6, 6]])

## seed 让随机数每次随机结果都一样

In [17]:
np.random.seed(333)#参数值必须有但随便取
np.random.randint(5,10,(2,4))

array([[9, 9, 8, 8],
       [9, 8, 9, 7]])

## randn 生成具有标准正态分布的随机数

In [42]:
np.random.randn(5)

array([ 0.52493957, -0.35783583, -0.72820492, -0.64208645, -0.31704766])

In [43]:
np.random.randn(2,4)

array([[-1.21900143, -0.05198034,  0.69402731, -0.12359776],
       [ 1.77361709,  0.27269254, -0.21295821, -0.47321244]])

## normal 设置均值和方差生成具有高斯分布的随机数据

In [44]:
np.random.normal()

-0.3135010787602591

In [45]:
np.random.normal(10,1000,20)#均值10，方差1000，最后一个为size参数

array([ 1631.67388376,   727.94926784, -2111.81291556,  -232.58443093,
        -816.81121939, -1267.4569926 ,   328.06252962,   277.17196915,
        1835.59468844,   162.47206197,   530.58481952, -1111.61661026,
        2173.06751556,  1704.88610756,  -575.16336901, -1012.49181678,
         441.55523899, -1159.36724734,  -699.09003393,  -401.25804659])

In [46]:
np.random.normal(10,1000,size=(2,4))

array([[ -976.93190412,  -521.80745013, -1820.64112767, -1215.90283091],
       [-1589.1719541 ,  -264.94728256,  -663.61570823,   373.18608305]])

## uniform生成具有均匀分布的随机数据

In [48]:
np.random.uniform()

0.3189467965274373

In [49]:
np.random.uniform(1,5)

4.110504530854963

In [50]:
np.random.uniform(1,5,(2,4))

array([[1.25758537, 4.97976231, 1.37368286, 4.05804776],
       [1.61887301, 3.22989502, 3.33332378, 3.23317518]])

## np.函数？查询该函数功能
## help(np.函数)

In [53]:
np.random.uniform?

In [54]:
help(np.random.uniform)

Help on built-in function uniform:

uniform(...) method of numpy.random.mtrand.RandomState instance
    uniform(low=0.0, high=1.0, size=None)
    
    Draw samples from a uniform distribution.
    
    Samples are uniformly distributed over the half-open interval
    ``[low, high)`` (includes low, but excludes high).  In other words,
    any value within the given interval is equally likely to be drawn
    by `uniform`.
    
    .. note::
        New code should use the `~numpy.random.Generator.uniform`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : float or array_like of floats, optional
        Lower boundary of the output interval.  All values generated will be
        greater than or equal to low.  The default value is 0.
    high : float or array_like of floats
        Upper boundary of the output interval.  All values generated will be
        less than or equal to high