# 基础索引

In [1]:
import numpy as np

In [2]:
# 一维数组也看做向量
# 一般用小写字母表示
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
#二维数组 也看做：矩阵
#一般用大写字母表示
A=np.arange(20).reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## 一维数组

In [4]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a[0]

0

In [6]:
a[4]

4

In [7]:
a[-1]

9

In [8]:
a[0:5]#5取不到

array([0, 1, 2, 3, 4])

In [9]:
a[:5]#0到5不含5

array([0, 1, 2, 3, 4])

In [10]:
a[4:]#从4取到最后

array([4, 5, 6, 7, 8, 9])

In [11]:
a[-3:]#倒数取到最后

array([7, 8, 9])

In [12]:
a[:]#从头取到最后

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
a[::2]#从头取到最后步长为2

array([0, 2, 4, 6, 8])

In [14]:
a[::-1]#倒着取步长1

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [35]:
a[7::-2]#从第7个开始倒着取，步长为2

array([7, 5, 3, 1])

## 二维数组

In [16]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [17]:
A[0,0]#第一个行索引第二个列索引

0

In [18]:
A[0,:]#第一行所有元素，与A[0]同

array([0, 1, 2, 3, 4])

In [19]:
A[-1]#倒数第一行

array([15, 16, 17, 18, 19])

In [20]:
A[:,0]#第一列所有数据

array([ 0,  5, 10, 15])

In [21]:
A[:,-1]#最后一列数据

array([ 4,  9, 14, 19])

In [22]:
A[:2,:4]#前两行前四列数据

array([[0, 1, 2, 3],
       [5, 6, 7, 8]])

In [23]:
A[::-1,::-1]##矩阵每行每列倒着取步长1

array([[19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

## Numpy切片修改会修改原数据
### 切片与原数组是绑定的关系一个改变都改变

In [24]:
X=A[:2,:3]
X

array([[0, 1, 2],
       [5, 6, 7]])

In [25]:
X[0,0]=666
X

array([[666,   1,   2],
       [  5,   6,   7]])

In [26]:
A

array([[666,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19]])

In [27]:
A[0,0]=0
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [28]:
X

array([[0, 1, 2],
       [5, 6, 7]])

## 防止切片变化原数组变化可以调用copy方法

In [29]:
X=A[:2,:3].copy()
X

array([[0, 1, 2],
       [5, 6, 7]])

In [30]:
X[0,0]=666
X

array([[666,   1,   2],
       [  5,   6,   7]])

In [31]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])