# 数组的合并
## concatenate
## vstack
## hstack都是传入元组

In [1]:
import numpy as np

In [2]:
X=np.arange(12).reshape(3,4)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
a=np.array([6,6,6,6])
a

array([6, 6, 6, 6])

## concatenate传入一个元组，元组里是要执行合并操作的数组，且二者维度相同

In [4]:
np.concatenate((X,a.reshape(1,4)))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 6,  6,  6,  6]])

In [5]:
np.concatenate((X,a.reshape(1,4)))#两个数组维度相同，前为二维后为一维，故后reshape

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 6,  6,  6,  6]])

In [6]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
a#合并后aX不改变，若要保存赋值给变量

array([6, 6, 6, 6])

In [8]:
A=np.concatenate((X,a.reshape(1,4)))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 6,  6,  6,  6]])

## vstack列方向合并行数增加

In [9]:
np.vstack((X,a))#传入一个元组，且维度不用相同，两个矩阵是竖直方向上的合并

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 6,  6,  6,  6]])

In [10]:
B=np.full((3,2),666)
B

array([[666, 666],
       [666, 666],
       [666, 666]])

## hstack行方向合并，列数增加

In [11]:
np.hstack((X,B))

array([[  0,   1,   2,   3, 666, 666],
       [  4,   5,   6,   7, 666, 666],
       [  8,   9,  10,  11, 666, 666]])

In [12]:
np.concatenate((X,B),axis=1)

array([[  0,   1,   2,   3, 666, 666],
       [  4,   5,   6,   7, 666, 666],
       [  8,   9,  10,  11, 666, 666]])

# 数组的拆分
## split
## vsplit
## hsplit

In [13]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## split（矩阵，拆分的哪一行或列，axis=0/1，默认值为0(列)）

In [14]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
np.split(X,[-1])#np.split(X,[-1],axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]])]

In [16]:
np.split(X,[-1],axis=1)

[array([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [17]:
X1,X2=np.split(X,[-1],axis=1)

In [18]:
X1

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [19]:
X2

array([[ 3],
       [ 7],
       [11]])

### vsplit

In [20]:
np.vsplit(X,[2])#拆分为[0:2]{2:}

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]])]

### hsplit

In [21]:
np.hsplit(X,[1,3])#拆分为[0:1][1:3][3:]

[array([[0],
        [4],
        [8]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]),
 array([[ 3],
        [ 7],
        [11]])]