# 数据准备

In [1]:
import numpy as np
state=np.array(['认真复习','简单复习','没有复习'])
grade=np.array(['A+','A','A-','B+','B','B-','C+','C','C-'])
n_state=len(state)
m_grade=len(grade)
pi=np.ones(n_state)/n_state
t=np.array([
    [0.4,0.3,0.3],
    [0.3,0.4,0.3],
    [0.3,0.3,0.4]
])
e=np.zeros([3,9])
e[0,:9]=1/9
e[1,3:9]=1/6
e[2,5:9]=1/4

In [2]:
print("初始概率矩阵:\n",pi)
print("转移矩阵:\n",t)
print("发射矩阵:\n",e)

初始概率矩阵:
 [0.33333333 0.33333333 0.33333333]
转移矩阵:
 [[0.4 0.3 0.3]
 [0.3 0.4 0.3]
 [0.3 0.3 0.4]]
发射矩阵:
 [[0.11111111 0.11111111 0.11111111 0.11111111 0.11111111 0.11111111
  0.11111111 0.11111111 0.11111111]
 [0.         0.         0.         0.16666667 0.16666667 0.16666667
  0.16666667 0.16666667 0.16666667]
 [0.         0.         0.         0.         0.         0.25
  0.25       0.25       0.25      ]]


# hmmlearn

In [3]:
from hmmlearn.hmm import CategoricalHMM
hmm=CategoricalHMM(n_state)

In [7]:
hmm.startprob_=pi
hmm.transmat_=t
hmm.emissionprob_=e
hmm.n_features=9#观测值个数

In [10]:
datas=np.array([0,4,2,6,1])
datas=np.expand_dims(datas,axis=1)
states=hmm.predict(datas)

In [11]:
states

array([0, 0, 0, 2, 0], dtype=int64)

In [12]:
prob=hmm.score(datas)
prob

-14.003674820375014

In [13]:
print(np.exp(prob))

8.284786081615825e-07


## hmm生成满足三要素约束的数据

In [14]:
datas,states=hmm.sample(10000)

In [15]:
t_2=np.zeros([3,3])
for i in range(3):
    current=np.where(states==i)[0]
    next_index=current+1
    next_index=next_index[:-1]
    
    tmp=states[next_index]
    for j in range(3):
        t_2[i][j]=np.where(tmp==j)[0].shape[0]/np.shape(tmp)[0]
print(t_2)

[[0.40910426 0.29162996 0.29926579]
 [0.31485519 0.3889754  0.29616942]
 [0.29606625 0.28630583 0.41762792]]


In [17]:
e_2=np.zeros([3,9])
for i in range(3):
    current=np.where(states==i)[0]
    next_index=current+1
    next_index=next_index[:-1]
    
    tmp=states[next_index]
    for j in range(9):
        e_2[i][j]=np.where(tmp==j)[0].shape[0]/np.shape(tmp)[0]
print(e_2)

[[0.40910426 0.29162996 0.29926579 0.         0.         0.
  0.         0.         0.        ]
 [0.31485519 0.3889754  0.29616942 0.         0.         0.
  0.         0.         0.        ]
 [0.29606625 0.28630583 0.41762792 0.         0.         0.
  0.         0.         0.        ]]
